/**
 * tests/make-preview.js - dev only:  node tests/make-preview.js [--check]
 *
 * Writes tests/preview.html from index.html: the same page, paths one
 * folder up, plus memory-storage.js and preview.js before app.js. Run it
 * whenever index.html changes. --check only compares and exits 1 when
 * preview.html is out of date (app-smoke.js runs that check).
 */
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');

function build() {
  let html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  html = html.replace(/(href|src)="(css|js|vendor)\//g, '$1="../$2/');
  html = html.replace('<title>Metrology Request Tracker</title>', '<title>Metrology Request Tracker - preview</title>');
  html = html.replace('<head>', '<head>\n<!-- GENERATED by tests/make-preview.js from index.html - do not edit by hand.\n     Dev only: the real app on demo data, in memory. See tests/preview.js. -->');
  const app = '<script src="../js/app.js"></script>';
  if (html.indexOf(app) === -1) throw new Error('index.html has no js/app.js script');
  html = html.replace(app, '<!-- dev only: a memory folder with demo data instead of the data folder -->\n' +
    '<script src="memory-storage.js"></script>\n<script src="demo-data.js"></script>\n<script src="preview.js"></script>\n' + app);
  return html;
}

const out = path.join(__dirname, 'preview.html');
const html = build();
if (process.argv[2] === '--check') {
  const same = fs.existsSync(out) && fs.readFileSync(out, 'utf8') === html;
  console.log(same ? 'preview.html is up to date' : 'preview.html is OUT OF DATE - run: node tests/make-preview.js');
  if (!same) process.exitCode = 1;
} else {
  fs.writeFileSync(out, html);
  console.log('wrote tests/preview.html');
}
